version: '3'

services:
  
  mongo:
    image: mongo
    container_name: mongo
    environment:
      - MONGO_DATA_DIR=/data/db
    volumes:
      - ./data/mongo:/data/db
    ports:
        - 27017:27017
  dash:
    build: .
    ports:
     - "8888:8888"
    volumes:
      - ./:/app
  